# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cd_normalCC <- function(X, y, alpha, lambda_vec, maxit = 10000L, tol = 1e-7, standardize = TRUE) {
    .Call('_mylmnet_cd_normalCC', PACKAGE = 'mylmnet', X, y, alpha, lambda_vec, maxit, tol, standardize)
}

